'------------------------------------------------------------------------------
' <auto-generated>
'     Ten kod został wygenerowany przez narzędzie.
'     Wersja wykonawcza:4.0.30319.42000
'
'     Zmiany w tym pliku mogą spowodować nieprawidłowe zachowanie i zostaną utracone, jeśli
'     kod zostanie ponownie wygenerowany.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'Ta klasa została automatycznie wygenerowana za pomocą klasy StronglyTypedResourceBuilder
    'przez narzędzie, takie jak ResGen lub Visual Studio.
    'Aby dodać lub usunąć składową, edytuj plik ResX, a następnie ponownie uruchom narzędzie ResGen
    'z opcją /str lub ponownie utwórz projekt VS.
    '''<summary>
    '''  Klasa zasobu wymagająca zdefiniowania typu do wyszukiwania zlokalizowanych ciągów itd.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class resGlobal
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''Zwraca buforowane wystąpienie ResourceManager używane przez tę klasę.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Test.resGlobal", GetType(resGlobal).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Przesłania właściwość CurrentUICulture bieżącego wątku dla wszystkich
        '''  przypadków przeszukiwania zasobów za pomocą tej klasy zasobów wymagającej zdefiniowania typu.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''Wyszukuje zlokalizowany ciąg podobny do ciągu {0} is already opened.
        '''</summary>
        Friend Shared ReadOnly Property Msg_IsAlreadyOpened() As String
            Get
                Return ResourceManager.GetString("Msg_IsAlreadyOpened", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''Wyszukuje zlokalizowany ciąg podobny do ciągu Are you sure the entry should be deleted?.
        '''</summary>
        Friend Shared ReadOnly Property MsgAreYouSureSelectedEntryShouldBeDeleted() As String
            Get
                Return ResourceManager.GetString("MsgAreYouSureSelectedEntryShouldBeDeleted", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''Wyszukuje zlokalizowany ciąg podobny do ciągu Because in the meantime a new version of the program was recorded, the program is terminated automatically now. Please restart the program..
        '''</summary>
        Friend Shared ReadOnly Property MsgBecauseInMeantimeNewVersionOfProgramWasRecordedProgramIsTerminatedAutomaticallyNowPleaseRestart() As String
            Get
                Return ResourceManager.GetString("MsgBecauseInMeantimeNewVersionOfProgramWasRecordedProgramIsTerminatedAutomaticall"& _ 
                        "yNowPleaseRestart", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''Wyszukuje zlokalizowany ciąg podobny do ciągu Because a new version of the program is recorded, the program is terminated automatically now. Please restart the program..
        '''</summary>
        Friend Shared ReadOnly Property MsgBecauseNewVersionOfProgramIsRecordedProgramIsTerminatedAutomaticallyNowPleaseRestartProgram() As String
            Get
                Return ResourceManager.GetString("MsgBecauseNewVersionOfProgramIsRecordedProgramIsTerminatedAutomaticallyNowPleaseR"& _ 
                        "estartProgram", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''Wyszukuje zlokalizowany ciąg podobny do ciągu Cant write file &apos;{0}&apos;..
        '''</summary>
        Friend Shared ReadOnly Property MsgCantWriteFile_() As String
            Get
                Return ResourceManager.GetString("MsgCantWriteFile_", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''Wyszukuje zlokalizowany ciąg podobny do ciągu clsDataReader: object &apos;{0}&apos; not found.
        '''</summary>
        Friend Shared ReadOnly Property MsgClsDataReaderObject_NotFound() As String
            Get
                Return ResourceManager.GetString("MsgClsDataReaderObject_NotFound", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''Wyszukuje zlokalizowany ciąg podobny do ciągu Database file &apos;{0}&apos; is missing..
        '''</summary>
        Friend Shared ReadOnly Property MsgDatabaseFile_IsMissing() As String
            Get
                Return ResourceManager.GetString("MsgDatabaseFile_IsMissing", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''Wyszukuje zlokalizowany ciąg podobny do ciągu Data saved..
        '''</summary>
        Friend Shared ReadOnly Property MsgDataSaved() As String
            Get
                Return ResourceManager.GetString("MsgDataSaved", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''Wyszukuje zlokalizowany ciąg podobny do ciągu Data type &apos;{0}&apos; is not supported..
        '''</summary>
        Friend Shared ReadOnly Property MsgDataType_IsNotSupported() As String
            Get
                Return ResourceManager.GetString("MsgDataType_IsNotSupported", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''Wyszukuje zlokalizowany ciąg podobny do ciągu The document &apos;{0}&apos; could not be found..
        '''</summary>
        Friend Shared ReadOnly Property MsgDocument_CouldNotBeFound() As String
            Get
                Return ResourceManager.GetString("MsgDocument_CouldNotBeFound", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''Wyszukuje zlokalizowany ciąg podobny do ciągu Document could not be loaded!.
        '''</summary>
        Friend Shared ReadOnly Property MsgDocumentCouldNotBeLoaded() As String
            Get
                Return ResourceManager.GetString("MsgDocumentCouldNotBeLoaded", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''Wyszukuje zlokalizowany ciąg podobny do ciągu Do you want to exit the application?.
        '''</summary>
        Friend Shared ReadOnly Property MsgDoYouWantToExitApplication() As String
            Get
                Return ResourceManager.GetString("MsgDoYouWantToExitApplication", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''Wyszukuje zlokalizowany ciąg podobny do ciągu Do you want to save the changes before closing?.
        '''</summary>
        Friend Shared ReadOnly Property MsgDoYouWantToSaveChangesBeforeClosing() As String
            Get
                Return ResourceManager.GetString("MsgDoYouWantToSaveChangesBeforeClosing", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''Wyszukuje zlokalizowany ciąg podobny do ciągu The end date is before the start date..
        '''</summary>
        Friend Shared ReadOnly Property MsgEndDateIsBeforeStartDate() As String
            Get
                Return ResourceManager.GetString("MsgEndDateIsBeforeStartDate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''Wyszukuje zlokalizowany ciąg podobny do ciągu Error accessing SCD: SCD-GID &apos;{0}&apos; is not unique..
        '''</summary>
        Friend Shared ReadOnly Property MsgErrorAccessingSCDSCDGID_IsNotUnique() As String
            Get
                Return ResourceManager.GetString("MsgErrorAccessingSCDSCDGID_IsNotUnique", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''Wyszukuje zlokalizowany ciąg podobny do ciągu Error in the method &apos;{0}&apos; ({1}).
        '''</summary>
        Friend Shared ReadOnly Property MsgErrorInMethod_() As String
            Get
                Return ResourceManager.GetString("MsgErrorInMethod_", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''Wyszukuje zlokalizowany ciąg podobny do ciągu Error in the statement execution {0}:.
        '''</summary>
        Friend Shared ReadOnly Property MsgErrorInStatementExecution_() As String
            Get
                Return ResourceManager.GetString("MsgErrorInStatementExecution_", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''Wyszukuje zlokalizowany ciąg podobny do ciągu An error occured! ({0}).
        '''</summary>
        Friend Shared ReadOnly Property MsgErrorOccured_() As String
            Get
                Return ResourceManager.GetString("MsgErrorOccured_", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''Wyszukuje zlokalizowany ciąg podobny do ciągu Error opening DataReader for {0}:.
        '''</summary>
        Friend Shared ReadOnly Property MsgErrorOpeningDataReaderFor_() As String
            Get
                Return ResourceManager.GetString("MsgErrorOpeningDataReaderFor_", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''Wyszukuje zlokalizowany ciąg podobny do ciągu Error while accessing last write time for file &apos;{0}&apos;.
        '''</summary>
        Friend Shared ReadOnly Property MsgErrorWhileAccessingLastWriteTime4File_() As String
            Get
                Return ResourceManager.GetString("MsgErrorWhileAccessingLastWriteTime4File_", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''Wyszukuje zlokalizowany ciąg podobny do ciągu Error while checking the availability of directory for &apos;{0}&apos; with search pattern &apos;{1}&apos;:.
        '''</summary>
        Friend Shared ReadOnly Property MsgErrorWhileCheckingAvailabilityOfDirectory4_WithSearchPattern_() As String
            Get
                Return ResourceManager.GetString("MsgErrorWhileCheckingAvailabilityOfDirectory4_WithSearchPattern_", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''Wyszukuje zlokalizowany ciąg podobny do ciągu Error while copying file &apos;{0}&apos;:.
        '''</summary>
        Friend Shared ReadOnly Property MsgErrorWhileCopyingFile_DestinationDirectory_NotAvailableOrUserIsNotAuthorized() As String
            Get
                Return ResourceManager.GetString("MsgErrorWhileCopyingFile_DestinationDirectory_NotAvailableOrUserIsNotAuthorized", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''Wyszukuje zlokalizowany ciąg podobny do ciągu Error while copying file &apos;{0}&apos;: file is already available, overwriting not intended..
        '''</summary>
        Friend Shared ReadOnly Property MsgErrorWhileCopyingFile_FileIsAlreadyAvailableOverwritingNotIntended() As String
            Get
                Return ResourceManager.GetString("MsgErrorWhileCopyingFile_FileIsAlreadyAvailableOverwritingNotIntended", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''Wyszukuje zlokalizowany ciąg podobny do ciągu Error while copying the template file &apos;{0}&apos; to &apos;{1}&apos;..
        '''</summary>
        Friend Shared ReadOnly Property MsgErrorWhileCopyingTemplateFile_To_() As String
            Get
                Return ResourceManager.GetString("MsgErrorWhileCopyingTemplateFile_To_", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''Wyszukuje zlokalizowany ciąg podobny do ciągu Error while creating the directory &apos;{0}&apos;:.
        '''</summary>
        Friend Shared ReadOnly Property MsgErrorWhileCreatingDirectory_() As String
            Get
                Return ResourceManager.GetString("MsgErrorWhileCreatingDirectory_", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''Wyszukuje zlokalizowany ciąg podobny do ciągu Error while deleting directory &apos;{0}&apos;:.
        '''</summary>
        Friend Shared ReadOnly Property MsgErrorWhileDeletingDirectory_() As String
            Get
                Return ResourceManager.GetString("MsgErrorWhileDeletingDirectory_", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''Wyszukuje zlokalizowany ciąg podobny do ciągu Error while deleting file &apos;{0}&apos;..
        '''</summary>
        Friend Shared ReadOnly Property MsgErrorWhileDeletingFile_PleaseDeleteFileManually() As String
            Get
                Return ResourceManager.GetString("MsgErrorWhileDeletingFile_PleaseDeleteFileManually", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''Wyszukuje zlokalizowany ciąg podobny do ciągu Error while executing the scalar instruction {0}:.
        '''</summary>
        Friend Shared ReadOnly Property MsgErrorWhileExecutingScalarInstruction_() As String
            Get
                Return ResourceManager.GetString("MsgErrorWhileExecutingScalarInstruction_", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''Wyszukuje zlokalizowany ciąg podobny do ciągu Error while moving file &apos;{0}&apos; to &apos;{1}&apos;:.
        '''</summary>
        Friend Shared ReadOnly Property MsgErrorWhileMovingFile_To_() As String
            Get
                Return ResourceManager.GetString("MsgErrorWhileMovingFile_To_", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''Wyszukuje zlokalizowany ciąg podobny do ciągu Error while opening database. Connection String: {0}.
        '''</summary>
        Friend Shared ReadOnly Property MsgErrorWhileOpeningDatabaseConnectionString_() As String
            Get
                Return ResourceManager.GetString("MsgErrorWhileOpeningDatabaseConnectionString_", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''Wyszukuje zlokalizowany ciąg podobny do ciągu Error while opening directory &apos;{0}&apos;:.
        '''</summary>
        Friend Shared ReadOnly Property MsgErrorWhileOpeningDirectory_() As String
            Get
                Return ResourceManager.GetString("MsgErrorWhileOpeningDirectory_", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''Wyszukuje zlokalizowany ciąg podobny do ciągu Error while opening document &apos;{0}&apos;..
        '''</summary>
        Friend Shared ReadOnly Property MsgErrorWhileOpeningDocument_() As String
            Get
                Return ResourceManager.GetString("MsgErrorWhileOpeningDocument_", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''Wyszukuje zlokalizowany ciąg podobny do ciągu Error while relocking the record. Please report this error to your administrator..
        '''</summary>
        Friend Shared ReadOnly Property MsgErrorWhileRelockingRecordPleaseReportThisErrorToYourAdministrator() As String
            Get
                Return ResourceManager.GetString("MsgErrorWhileRelockingRecordPleaseReportThisErrorToYourAdministrator", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''Wyszukuje zlokalizowany ciąg podobny do ciągu Error while searching file &apos;{0}&apos;:.
        '''</summary>
        Friend Shared ReadOnly Property MsgErrorWhileSearchingFile_() As String
            Get
                Return ResourceManager.GetString("MsgErrorWhileSearchingFile_", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''Wyszukuje zlokalizowany ciąg podobny do ciągu Failed to create the database connection..
        '''</summary>
        Friend Shared ReadOnly Property MsgFailedToCreateDatabaseConnection() As String
            Get
                Return ResourceManager.GetString("MsgFailedToCreateDatabaseConnection", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''Wyszukuje zlokalizowany ciąg podobny do ciągu Failed to open the file &apos;{0}&apos; (&quot; {1} &quot;)..
        '''</summary>
        Friend Shared ReadOnly Property MsgFailedToOpenFile_() As String
            Get
                Return ResourceManager.GetString("MsgFailedToOpenFile_", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''Wyszukuje zlokalizowany ciąg podobny do ciągu The file &apos;{0}&apos; could not be copied to &apos;{1}&apos;!.
        '''</summary>
        Friend Shared ReadOnly Property MsgFile_CouldNotBeCopiedTo_() As String
            Get
                Return ResourceManager.GetString("MsgFile_CouldNotBeCopiedTo_", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''Wyszukuje zlokalizowany ciąg podobny do ciągu The file &apos;{0}&apos; does not exist..
        '''</summary>
        Friend Shared ReadOnly Property MsgFile_DoesNotExist() As String
            Get
                Return ResourceManager.GetString("MsgFile_DoesNotExist", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''Wyszukuje zlokalizowany ciąg podobny do ciągu Function is not yet implemented..
        '''</summary>
        Friend Shared ReadOnly Property MsgFunctionIsNotYetImplemented() As String
            Get
                Return ResourceManager.GetString("MsgFunctionIsNotYetImplemented", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''Wyszukuje zlokalizowany ciąg podobny do ciągu Gathering information....
        '''</summary>
        Friend Shared ReadOnly Property MsgGatheringInformation() As String
            Get
                Return ResourceManager.GetString("MsgGatheringInformation", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''Wyszukuje zlokalizowany ciąg podobny do ciągu Ini file &apos;{0}&apos; is missing..
        '''</summary>
        Friend Shared ReadOnly Property MsgIniFile_IsMissing() As String
            Get
                Return ResourceManager.GetString("MsgIniFile_IsMissing", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''Wyszukuje zlokalizowany ciąg podobny do ciągu Invalid Connection String &apos;{0}&apos;..
        '''</summary>
        Friend Shared ReadOnly Property MsgInvalidConnectionString_() As String
            Get
                Return ResourceManager.GetString("MsgInvalidConnectionString_", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''Wyszukuje zlokalizowany ciąg podobny do ciągu Invalid database file name &apos;{0}&apos; in .ini file..
        '''</summary>
        Friend Shared ReadOnly Property MsgInvalidDatabaseFileName_InIniFile() As String
            Get
                Return ResourceManager.GetString("MsgInvalidDatabaseFileName_InIniFile", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''Wyszukuje zlokalizowany ciąg podobny do ciągu The key &apos;{0}&apos; could not be found..
        '''</summary>
        Friend Shared ReadOnly Property MsgKey_CouldNotBeFound() As String
            Get
                Return ResourceManager.GetString("MsgKey_CouldNotBeFound", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''Wyszukuje zlokalizowany ciąg podobny do ciągu Moving file ....
        '''</summary>
        Friend Shared ReadOnly Property MsgMovingFile() As String
            Get
                Return ResourceManager.GetString("MsgMovingFile", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''Wyszukuje zlokalizowany ciąg podobny do ciągu Not found..
        '''</summary>
        Friend Shared ReadOnly Property MsgNotFound() As String
            Get
                Return ResourceManager.GetString("MsgNotFound", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''Wyszukuje zlokalizowany ciąg podobny do ciągu Number of connections:.
        '''</summary>
        Friend Shared ReadOnly Property MsgNumberOfConnections() As String
            Get
                Return ResourceManager.GetString("MsgNumberOfConnections", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''Wyszukuje zlokalizowany ciąg podobny do ciągu Open folder &apos;{0}&apos;.
        '''</summary>
        Friend Shared ReadOnly Property MsgOpenFolder_() As String
            Get
                Return ResourceManager.GetString("MsgOpenFolder_", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''Wyszukuje zlokalizowany ciąg podobny do ciągu Path &apos;{0}&apos; could not be created..
        '''</summary>
        Friend Shared ReadOnly Property MsgPath_CouldNotBeCreated() As String
            Get
                Return ResourceManager.GetString("MsgPath_CouldNotBeCreated", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''Wyszukuje zlokalizowany ciąg podobny do ciągu Please enter material number..
        '''</summary>
        Friend Shared ReadOnly Property MsgPleaseEnterMaterialNo() As String
            Get
                Return ResourceManager.GetString("MsgPleaseEnterMaterialNo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''Wyszukuje zlokalizowany ciąg podobny do ciągu Please enter a name!.
        '''</summary>
        Friend Shared ReadOnly Property MsgPleaseEnterName() As String
            Get
                Return ResourceManager.GetString("MsgPleaseEnterName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''Wyszukuje zlokalizowany ciąg podobny do ciągu Please enter a valid date..
        '''</summary>
        Friend Shared ReadOnly Property MsgPleaseEnterValidDate() As String
            Get
                Return ResourceManager.GetString("MsgPleaseEnterValidDate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''Wyszukuje zlokalizowany ciąg podobny do ciągu Please select at least one cell..
        '''</summary>
        Friend Shared ReadOnly Property MsgPleaseSelectAtLeastOneCell() As String
            Get
                Return ResourceManager.GetString("MsgPleaseSelectAtLeastOneCell", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''Wyszukuje zlokalizowany ciąg podobny do ciągu Please select an entry..
        '''</summary>
        Friend Shared ReadOnly Property MsgPleaseSelectEntry() As String
            Get
                Return ResourceManager.GetString("MsgPleaseSelectEntry", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''Wyszukuje zlokalizowany ciąg podobny do ciągu Please select an image file..
        '''</summary>
        Friend Shared ReadOnly Property MsgPleaseSelectImageFile() As String
            Get
                Return ResourceManager.GetString("MsgPleaseSelectImageFile", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''Wyszukuje zlokalizowany ciąg podobny do ciągu Please select only one row..
        '''</summary>
        Friend Shared ReadOnly Property MsgPleaseSelectOnlyOneRow() As String
            Get
                Return ResourceManager.GetString("MsgPleaseSelectOnlyOneRow", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''Wyszukuje zlokalizowany ciąg podobny do ciągu Please select a status!.
        '''</summary>
        Friend Shared ReadOnly Property MsgPleaseSelectStatus() As String
            Get
                Return ResourceManager.GetString("MsgPleaseSelectStatus", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''Wyszukuje zlokalizowany ciąg podobny do ciągu Please specify an existing directory..
        '''</summary>
        Friend Shared ReadOnly Property MsgPleaseSpecifyAnExistingDirectory() As String
            Get
                Return ResourceManager.GetString("MsgPleaseSpecifyAnExistingDirectory", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''Wyszukuje zlokalizowany ciąg podobny do ciągu Please specify an existing destination directory..
        '''</summary>
        Friend Shared ReadOnly Property MsgPleaseSpecifyExistingDestinationDirectory() As String
            Get
                Return ResourceManager.GetString("MsgPleaseSpecifyExistingDestinationDirectory", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''Wyszukuje zlokalizowany ciąg podobny do ciągu Please specify an existing source file..
        '''</summary>
        Friend Shared ReadOnly Property MsgPleaseSpecifyExistingSourceFile() As String
            Get
                Return ResourceManager.GetString("MsgPleaseSpecifyExistingSourceFile", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''Wyszukuje zlokalizowany ciąg podobny do ciągu Preparing file....
        '''</summary>
        Friend Shared ReadOnly Property MsgPreparingFile() As String
            Get
                Return ResourceManager.GetString("MsgPreparingFile", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''Wyszukuje zlokalizowany ciąg podobny do ciągu The program cannot be started because of missing permissions for running .NET programs from the security zone &apos;Local intranet&apos;. Please contact your system administrator..
        '''</summary>
        Friend Shared ReadOnly Property MsgProgramCannotBeStartedBecauseOfMissingPermissions4RunningDotNetProgramsFromSecurityZoneLocalIntranet() As String
            Get
                Return ResourceManager.GetString("MsgProgramCannotBeStartedBecauseOfMissingPermissions4RunningDotNetProgramsFromSec"& _ 
                        "urityZoneLocalIntranet", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''Wyszukuje zlokalizowany ciąg podobny do ciągu The program file you have started is not up-to-date. The current version number is &apos;{0}.{1}&apos;. Please ask your administrator for a new version..
        '''</summary>
        Friend Shared ReadOnly Property MsgProgramFileYouHaveStartedIsNotUpToDateCurrentVersionNumberIs_() As String
            Get
                Return ResourceManager.GetString("MsgProgramFileYouHaveStartedIsNotUpToDateCurrentVersionNumberIs_", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''Wyszukuje zlokalizowany ciąg podobny do ciągu The record could not be locked. At the moment it is in process by &apos;{0}&apos; (computer &apos;{1}&apos;)..
        '''</summary>
        Friend Shared ReadOnly Property MsgRecordCouldNotBeLockedAtMomentItIsInProcessBy_Computer_() As String
            Get
                Return ResourceManager.GetString("MsgRecordCouldNotBeLockedAtMomentItIsInProcessBy_Computer_", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''Wyszukuje zlokalizowany ciąg podobny do ciągu Source directory does not exist: {0}.
        '''</summary>
        Friend Shared ReadOnly Property MsgSourceDirectoryDoesNotExist_() As String
            Get
                Return ResourceManager.GetString("MsgSourceDirectoryDoesNotExist_", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''Wyszukuje zlokalizowany ciąg podobny do ciągu Target directory does not exist: {0}.
        '''</summary>
        Friend Shared ReadOnly Property MsgTargetDirectoryDoesNotExist_() As String
            Get
                Return ResourceManager.GetString("MsgTargetDirectoryDoesNotExist_", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''Wyszukuje zlokalizowany ciąg podobny do ciągu The template file &apos;{0}&apos; could not be found..
        '''</summary>
        Friend Shared ReadOnly Property MsgTemplateFile_CouldNotBeFound() As String
            Get
                Return ResourceManager.GetString("MsgTemplateFile_CouldNotBeFound", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''Wyszukuje zlokalizowany ciąg podobny do ciągu Unexpectedly high number of database connections: {0}..
        '''</summary>
        Friend Shared ReadOnly Property MsgUnexpectedlyHighNumberOfDatabaseConnections_() As String
            Get
                Return ResourceManager.GetString("MsgUnexpectedlyHighNumberOfDatabaseConnections_", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''Wyszukuje zlokalizowany ciąg podobny do ciągu Action completed..
        '''</summary>
        Friend Shared ReadOnly Property TextActionCompleted() As String
            Get
                Return ResourceManager.GetString("TextActionCompleted", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''Wyszukuje zlokalizowany ciąg podobny do ciągu active.
        '''</summary>
        Friend Shared ReadOnly Property TextActive() As String
            Get
                Return ResourceManager.GetString("TextActive", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''Wyszukuje zlokalizowany ciąg podobny do ciągu Administrator.
        '''</summary>
        Friend Shared ReadOnly Property TextAdministrator() As String
            Get
                Return ResourceManager.GetString("TextAdministrator", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''Wyszukuje zlokalizowany ciąg podobny do ciągu (all).
        '''</summary>
        Friend Shared ReadOnly Property TextAll() As String
            Get
                Return ResourceManager.GetString("TextAll", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''Wyszukuje zlokalizowany ciąg podobny do ciągu All files.
        '''</summary>
        Friend Shared ReadOnly Property TextAllFiles() As String
            Get
                Return ResourceManager.GetString("TextAllFiles", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''Wyszukuje zlokalizowany ciąg podobny do ciągu  begins with:.
        '''</summary>
        Friend Shared ReadOnly Property TextBeginsWith() As String
            Get
                Return ResourceManager.GetString("TextBeginsWith", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''Wyszukuje zlokalizowany ciąg podobny do ciągu Cancel.
        '''</summary>
        Friend Shared ReadOnly Property TextCancel() As String
            Get
                Return ResourceManager.GetString("TextCancel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''Wyszukuje zlokalizowany ciąg podobny do ciągu Caused by the following inner exception:.
        '''</summary>
        Friend Shared ReadOnly Property TextCausedByFollowingInnerException() As String
            Get
                Return ResourceManager.GetString("TextCausedByFollowingInnerException", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''Wyszukuje zlokalizowany ciąg podobny do ciągu Close.
        '''</summary>
        Friend Shared ReadOnly Property TextClose() As String
            Get
                Return ResourceManager.GetString("TextClose", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''Wyszukuje zlokalizowany ciąg podobny do ciągu closed.
        '''</summary>
        Friend Shared ReadOnly Property TextClosed() As String
            Get
                Return ResourceManager.GetString("TextClosed", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''Wyszukuje zlokalizowany ciąg podobny do ciągu .csv files.
        '''</summary>
        Friend Shared ReadOnly Property TextCSVFiles() As String
            Get
                Return ResourceManager.GetString("TextCSVFiles", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''Wyszukuje zlokalizowany ciąg podobny do ciągu Description.
        '''</summary>
        Friend Shared ReadOnly Property TextDescription() As String
            Get
                Return ResourceManager.GetString("TextDescription", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''Wyszukuje zlokalizowany ciąg podobny do ciągu Done.
        '''</summary>
        Friend Shared ReadOnly Property TextDone() As String
            Get
                Return ResourceManager.GetString("TextDone", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''Wyszukuje zlokalizowany ciąg podobny do ciągu Edit.
        '''</summary>
        Friend Shared ReadOnly Property TextEdit() As String
            Get
                Return ResourceManager.GetString("TextEdit", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''Wyszukuje zlokalizowany ciąg podobny do ciągu Elements left:.
        '''</summary>
        Friend Shared ReadOnly Property TextElementsLeft() As String
            Get
                Return ResourceManager.GetString("TextElementsLeft", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''Wyszukuje zlokalizowany ciąg podobny do ciągu Error.
        '''</summary>
        Friend Shared ReadOnly Property TextError() As String
            Get
                Return ResourceManager.GetString("TextError", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''Wyszukuje zlokalizowany ciąg podobny do ciągu Filter:.
        '''</summary>
        Friend Shared ReadOnly Property TextFilter() As String
            Get
                Return ResourceManager.GetString("TextFilter", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''Wyszukuje zlokalizowany ciąg podobny do ciągu (found).
        '''</summary>
        Friend Shared ReadOnly Property TextFound() As String
            Get
                Return ResourceManager.GetString("TextFound", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''Wyszukuje zlokalizowany ciąg podobny do ciągu From:.
        '''</summary>
        Friend Shared ReadOnly Property TextFrom() As String
            Get
                Return ResourceManager.GetString("TextFrom", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''Wyszukuje zlokalizowany ciąg podobny do ciągu Guest.
        '''</summary>
        Friend Shared ReadOnly Property TextGuest() As String
            Get
                Return ResourceManager.GetString("TextGuest", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''Wyszukuje zlokalizowany ciąg podobny do ciągu Image files.
        '''</summary>
        Friend Shared ReadOnly Property TextImageFiles() As String
            Get
                Return ResourceManager.GetString("TextImageFiles", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''Wyszukuje zlokalizowany ciąg podobny do ciągu inactive.
        '''</summary>
        Friend Shared ReadOnly Property TextInactive() As String
            Get
                Return ResourceManager.GetString("TextInactive", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''Wyszukuje zlokalizowany ciąg podobny do ciągu Info.
        '''</summary>
        Friend Shared ReadOnly Property TextInfo() As String
            Get
                Return ResourceManager.GetString("TextInfo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''Wyszukuje zlokalizowany ciąg podobny do ciągu Information.
        '''</summary>
        Friend Shared ReadOnly Property TextInformation() As String
            Get
                Return ResourceManager.GetString("TextInformation", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''Wyszukuje zlokalizowany ciąg podobny do ciągu In process.
        '''</summary>
        Friend Shared ReadOnly Property TextInProcess() As String
            Get
                Return ResourceManager.GetString("TextInProcess", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''Wyszukuje zlokalizowany ciąg podobny do ciągu Internal error.
        '''</summary>
        Friend Shared ReadOnly Property TextInternalError() As String
            Get
                Return ResourceManager.GetString("TextInternalError", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''Wyszukuje zlokalizowany ciąg podobny do ciągu locked.
        '''</summary>
        Friend Shared ReadOnly Property TextLocked() As String
            Get
                Return ResourceManager.GetString("TextLocked", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''Wyszukuje zlokalizowany ciąg podobny do ciągu Name:.
        '''</summary>
        Friend Shared ReadOnly Property TextName() As String
            Get
                Return ResourceManager.GetString("TextName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''Wyszukuje zlokalizowany ciąg podobny do ciągu No.
        '''</summary>
        Friend Shared ReadOnly Property TextNo() As String
            Get
                Return ResourceManager.GetString("TextNo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''Wyszukuje zlokalizowany ciąg podobny do ciągu None.
        '''</summary>
        Friend Shared ReadOnly Property TextNone() As String
            Get
                Return ResourceManager.GetString("TextNone", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''Wyszukuje zlokalizowany ciąg podobny do ciągu (not found).
        '''</summary>
        Friend Shared ReadOnly Property TextNotFound() As String
            Get
                Return ResourceManager.GetString("TextNotFound", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''Wyszukuje zlokalizowany ciąg podobny do ciągu only.
        '''</summary>
        Friend Shared ReadOnly Property TextOnly() As String
            Get
                Return ResourceManager.GetString("TextOnly", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''Wyszukuje zlokalizowany ciąg podobny do ciągu Other.
        '''</summary>
        Friend Shared ReadOnly Property TextOther() As String
            Get
                Return ResourceManager.GetString("TextOther", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''Wyszukuje zlokalizowany ciąg podobny do ciągu .pdf files.
        '''</summary>
        Friend Shared ReadOnly Property TextPDFFiles() As String
            Get
                Return ResourceManager.GetString("TextPDFFiles", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''Wyszukuje zlokalizowany ciąg podobny do ciągu (please check).
        '''</summary>
        Friend Shared ReadOnly Property TextPleaseCheck() As String
            Get
                Return ResourceManager.GetString("TextPleaseCheck", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''Wyszukuje zlokalizowany ciąg podobny do ciągu (please select).
        '''</summary>
        Friend Shared ReadOnly Property TextPleaseSelect() As String
            Get
                Return ResourceManager.GetString("TextPleaseSelect", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''Wyszukuje zlokalizowany ciąg podobny do ciągu Quantity.
        '''</summary>
        Friend Shared ReadOnly Property TextQuantity() As String
            Get
                Return ResourceManager.GetString("TextQuantity", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''Wyszukuje zlokalizowany ciąg podobny do ciągu Question.
        '''</summary>
        Friend Shared ReadOnly Property TextQuestion() As String
            Get
                Return ResourceManager.GetString("TextQuestion", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''Wyszukuje zlokalizowany ciąg podobny do ciągu Released.
        '''</summary>
        Friend Shared ReadOnly Property TextReleased() As String
            Get
                Return ResourceManager.GetString("TextReleased", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''Wyszukuje zlokalizowany ciąg podobny do ciągu Release date.
        '''</summary>
        Friend Shared ReadOnly Property TextReleaseDate() As String
            Get
                Return ResourceManager.GetString("TextReleaseDate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''Wyszukuje zlokalizowany ciąg podobny do ciągu Released by.
        '''</summary>
        Friend Shared ReadOnly Property TextReleasedBy() As String
            Get
                Return ResourceManager.GetString("TextReleasedBy", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''Wyszukuje zlokalizowany ciąg podobny do ciągu Retry.
        '''</summary>
        Friend Shared ReadOnly Property TextRetry() As String
            Get
                Return ResourceManager.GetString("TextRetry", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''Wyszukuje zlokalizowany ciąg podobny do ciągu State:.
        '''</summary>
        Friend Shared ReadOnly Property TextState() As String
            Get
                Return ResourceManager.GetString("TextState", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''Wyszukuje zlokalizowany ciąg podobny do ciągu successfully completed.
        '''</summary>
        Friend Shared ReadOnly Property TextSuccessfullyCompleted() As String
            Get
                Return ResourceManager.GetString("TextSuccessfullyCompleted", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''Wyszukuje zlokalizowany ciąg podobny do ciągu Sum:.
        '''</summary>
        Friend Shared ReadOnly Property TextSum() As String
            Get
                Return ResourceManager.GetString("TextSum", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''Wyszukuje zlokalizowany ciąg podobny do ciągu terminated abnormally.
        '''</summary>
        Friend Shared ReadOnly Property TextTerminatedAbnormally() As String
            Get
                Return ResourceManager.GetString("TextTerminatedAbnormally", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''Wyszukuje zlokalizowany ciąg podobny do ciągu To:.
        '''</summary>
        Friend Shared ReadOnly Property TextTo() As String
            Get
                Return ResourceManager.GetString("TextTo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''Wyszukuje zlokalizowany ciąg podobny do ciągu User.
        '''</summary>
        Friend Shared ReadOnly Property TextUser() As String
            Get
                Return ResourceManager.GetString("TextUser", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''Wyszukuje zlokalizowany ciąg podobny do ciągu User.
        '''</summary>
        Friend Shared ReadOnly Property TextUser2() As String
            Get
                Return ResourceManager.GetString("TextUser2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''Wyszukuje zlokalizowany ciąg podobny do ciągu Value.
        '''</summary>
        Friend Shared ReadOnly Property TextValue() As String
            Get
                Return ResourceManager.GetString("TextValue", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''Wyszukuje zlokalizowany ciąg podobny do ciągu View.
        '''</summary>
        Friend Shared ReadOnly Property TextView() As String
            Get
                Return ResourceManager.GetString("TextView", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''Wyszukuje zlokalizowany ciąg podobny do ciągu (without).
        '''</summary>
        Friend Shared ReadOnly Property TextWithout() As String
            Get
                Return ResourceManager.GetString("TextWithout", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''Wyszukuje zlokalizowany ciąg podobny do ciągu Yes.
        '''</summary>
        Friend Shared ReadOnly Property TextYes() As String
            Get
                Return ResourceManager.GetString("TextYes", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
