'------------------------------------------------------------------------------
' <auto-generated>
'     Ten kod został wygenerowany przez narzędzie.
'     Wersja wykonawcza:4.0.30319.42000
'
'     Zmiany w tym pliku mogą spowodować nieprawidłowe zachowanie i zostaną utracone, jeśli
'     kod zostanie ponownie wygenerowany.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'Ta klasa została automatycznie wygenerowana za pomocą klasy StronglyTypedResourceBuilder
    'przez narzędzie, takie jak ResGen lub Visual Studio.
    'Aby dodać lub usunąć składową, edytuj plik ResX, a następnie ponownie uruchom narzędzie ResGen
    'z opcją /str lub ponownie utwórz projekt VS.
    '''<summary>
    '''  Klasa zasobu wymagająca zdefiniowania typu do wyszukiwania zlokalizowanych ciągów itd.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class resMain
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''Zwraca buforowane wystąpienie ResourceManager używane przez tę klasę.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Test.resMain", GetType(resMain).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Przesłania właściwość CurrentUICulture bieżącego wątku dla wszystkich
        '''  przypadków przeszukiwania zasobów za pomocą tej klasy zasobów wymagającej zdefiniowania typu.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''Wyszukuje zlokalizowany ciąg podobny do ciągu Are you sure the selected material should be removed from the list?.
        '''</summary>
        Friend Shared ReadOnly Property MsgAreYouSureSelectedMaterialShouldBeRemovedFromList() As String
            Get
                Return ResourceManager.GetString("MsgAreYouSureSelectedMaterialShouldBeRemovedFromList", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''Wyszukuje zlokalizowany ciąg podobny do ciągu Are you sure you want to delete the selected partner?.
        '''</summary>
        Friend Shared ReadOnly Property MsgAreYouSureYouWant2DeleteSelectedPartner() As String
            Get
                Return ResourceManager.GetString("MsgAreYouSureYouWant2DeleteSelectedPartner", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''Wyszukuje zlokalizowany ciąg podobny do ciągu Are you sure you want to delete the selected user?.
        '''</summary>
        Friend Shared ReadOnly Property MsgAreYouSureYouWant2DeleteSelectedUser() As String
            Get
                Return ResourceManager.GetString("MsgAreYouSureYouWant2DeleteSelectedUser", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''Wyszukuje zlokalizowany ciąg podobny do ciągu Are you sure you want to remove all materials from this folder?.
        '''</summary>
        Friend Shared ReadOnly Property MsgAreYouSureYouWantToRemoveAllMaterialsFromThisFolder() As String
            Get
                Return ResourceManager.GetString("MsgAreYouSureYouWantToRemoveAllMaterialsFromThisFolder", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''Wyszukuje zlokalizowany ciąg podobny do ciągu Are you sure you want to remove the selected materials from this folder?.
        '''</summary>
        Friend Shared ReadOnly Property MsgAreYouSureYouWantToRemoveSelectedMaterialsFromThisFolder() As String
            Get
                Return ResourceManager.GetString("MsgAreYouSureYouWantToRemoveSelectedMaterialsFromThisFolder", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''Wyszukuje zlokalizowany ciąg podobny do ciągu Cannot find dataset..
        '''</summary>
        Friend Shared ReadOnly Property MsgCannotFindDataset() As String
            Get
                Return ResourceManager.GetString("MsgCannotFindDataset", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''Wyszukuje zlokalizowany ciąg podobny do ciągu Check error log for details..
        '''</summary>
        Friend Shared ReadOnly Property MsgCheckErrorLogForDetails() As String
            Get
                Return ResourceManager.GetString("MsgCheckErrorLogForDetails", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''Wyszukuje zlokalizowany ciąg podobny do ciągu clsDataReader: Field {0} not found..
        '''</summary>
        Friend Shared ReadOnly Property MsgClsDatareaderFieldNotFound() As String
            Get
                Return ResourceManager.GetString("MsgClsDatareaderFieldNotFound", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''Wyszukuje zlokalizowany ciąg podobny do ciągu Could not determine the type of SAP export file!.
        '''</summary>
        Friend Shared ReadOnly Property MsgCouldNotDetermineTypeOfSAPExportFile() As String
            Get
                Return ResourceManager.GetString("MsgCouldNotDetermineTypeOfSAPExportFile", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''Wyszukuje zlokalizowany ciąg podobny do ciągu Could not find MTool project for order no.: &apos;{0}&apos;!.
        '''</summary>
        Friend Shared ReadOnly Property MsgCouldNotFindMToolProject4OrderNo() As String
            Get
                Return ResourceManager.GetString("MsgCouldNotFindMToolProject4OrderNo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''Wyszukuje zlokalizowany ciąg podobny do ciągu Could not find required data in the clipboard!.
        '''</summary>
        Friend Shared ReadOnly Property MsgCouldNotFindRequiredDataInTheClipboard() As String
            Get
                Return ResourceManager.GetString("MsgCouldNotFindRequiredDataInTheClipboard", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''Wyszukuje zlokalizowany ciąg podobny do ciągu Could not map &apos;{0}&apos; line {1} to SQL record..
        '''</summary>
        Friend Shared ReadOnly Property MsgCouldNotMapLineToSQLRecord() As String
            Get
                Return ResourceManager.GetString("MsgCouldNotMapLineToSQLRecord", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''Wyszukuje zlokalizowany ciąg podobny do ciągu Could not open MTool DB!.
        '''</summary>
        Friend Shared ReadOnly Property MsgCouldNotOpenMToolDB() As String
            Get
                Return ResourceManager.GetString("MsgCouldNotOpenMToolDB", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''Wyszukuje zlokalizowany ciąg podobny do ciągu The e-mail &apos;{0}&apos; already exists in the database!.
        '''</summary>
        Friend Shared ReadOnly Property MsgEMailAlreadyExistsInTheDatabase() As String
            Get
                Return ResourceManager.GetString("MsgEMailAlreadyExistsInTheDatabase", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''Wyszukuje zlokalizowany ciąg podobny do ciągu The end date is before the start date..
        '''</summary>
        Friend Shared ReadOnly Property MsgEndDateIsBeforeStartDate() As String
            Get
                Return ResourceManager.GetString("MsgEndDateIsBeforeStartDate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''Wyszukuje zlokalizowany ciąg podobny do ciągu Error in PrintTableInsertScript: .
        '''</summary>
        Friend Shared ReadOnly Property MsgErrorInPrintTableInsertScript() As String
            Get
                Return ResourceManager.GetString("MsgErrorInPrintTableInsertScript", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''Wyszukuje zlokalizowany ciąg podobny do ciągu Error when starting Excel. (&quot; {0} &quot;)..
        '''</summary>
        Friend Shared ReadOnly Property MsgErrorWhenStartingExcel_() As String
            Get
                Return ResourceManager.GetString("MsgErrorWhenStartingExcel_", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''Wyszukuje zlokalizowany ciąg podobny do ciągu Error while accessing SCD: given GID &apos;{0}&apos; is not unique..
        '''</summary>
        Friend Shared ReadOnly Property MsgErrorWhileAccessingSCDGivenGIDIsNotUnique() As String
            Get
                Return ResourceManager.GetString("MsgErrorWhileAccessingSCDGivenGIDIsNotUnique", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''Wyszukuje zlokalizowany ciąg podobny do ciągu Error while executing SQL command:.
        '''</summary>
        Friend Shared ReadOnly Property MsgErrorWhileExecutingSQLCommand() As String
            Get
                Return ResourceManager.GetString("MsgErrorWhileExecutingSQLCommand", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''Wyszukuje zlokalizowany ciąg podobny do ciągu Error while executing SQL query:.
        '''</summary>
        Friend Shared ReadOnly Property MsgErrorWhileExecutingSQLQuery() As String
            Get
                Return ResourceManager.GetString("MsgErrorWhileExecutingSQLQuery", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''Wyszukuje zlokalizowany ciąg podobny do ciągu Error while opening Logfile..
        '''</summary>
        Friend Shared ReadOnly Property MsgErrorWhileOpeningLogFile() As String
            Get
                Return ResourceManager.GetString("MsgErrorWhileOpeningLogFile", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''Wyszukuje zlokalizowany ciąg podobny do ciągu Error while opening recordset:.
        '''</summary>
        Friend Shared ReadOnly Property MsgErrorWhileOpeningRecordSet() As String
            Get
                Return ResourceManager.GetString("MsgErrorWhileOpeningRecordSet", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''Wyszukuje zlokalizowany ciąg podobny do ciągu Error while (re-)opening database:.
        '''</summary>
        Friend Shared ReadOnly Property MsgErrorWhileReopeningDatabase() As String
            Get
                Return ResourceManager.GetString("MsgErrorWhileReopeningDatabase", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''Wyszukuje zlokalizowany ciąg podobny do ciągu The execution of an SQL command failed..
        '''</summary>
        Friend Shared ReadOnly Property MsgExecutionOfSQLCommandFailed() As String
            Get
                Return ResourceManager.GetString("MsgExecutionOfSQLCommandFailed", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''Wyszukuje zlokalizowany ciąg podobny do ciągu The execution of an SQL query failed..
        '''</summary>
        Friend Shared ReadOnly Property MsgExecutionOfSQLQueryFailed() As String
            Get
                Return ResourceManager.GetString("MsgExecutionOfSQLQueryFailed", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''Wyszukuje zlokalizowany ciąg podobny do ciągu File &apos;{0}&apos; already exists!.
        '''</summary>
        Friend Shared ReadOnly Property MsgFileAlreadyExists() As String
            Get
                Return ResourceManager.GetString("MsgFileAlreadyExists", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''Wyszukuje zlokalizowany ciąg podobny do ciągu First check the material!.
        '''</summary>
        Friend Shared ReadOnly Property MsgFirstCheckMaterial() As String
            Get
                Return ResourceManager.GetString("MsgFirstCheckMaterial", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''Wyszukuje zlokalizowany ciąg podobny do ciągu Found and removed duplicate entries: ({0}).
        '''</summary>
        Friend Shared ReadOnly Property MsgFoundAndRemovedDuplicateEntries() As String
            Get
                Return ResourceManager.GetString("MsgFoundAndRemovedDuplicateEntries", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''Wyszukuje zlokalizowany ciąg podobny do ciągu Found unknown material numbers: {0}.
        '''</summary>
        Friend Shared ReadOnly Property MsgFoundUnknownMaterialNumbers() As String
            Get
                Return ResourceManager.GetString("MsgFoundUnknownMaterialNumbers", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''Wyszukuje zlokalizowany ciąg podobny do ciągu Import completed..
        '''</summary>
        Friend Shared ReadOnly Property MsgImportCompleted() As String
            Get
                Return ResourceManager.GetString("MsgImportCompleted", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''Wyszukuje zlokalizowany ciąg podobny do ciągu Import failed..
        '''</summary>
        Friend Shared ReadOnly Property MsgImportFailed() As String
            Get
                Return ResourceManager.GetString("MsgImportFailed", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''Wyszukuje zlokalizowany ciąg podobny do ciągu Import of &apos;{0}&apos; failed: .
        '''</summary>
        Friend Shared ReadOnly Property MsgImportOfFailed() As String
            Get
                Return ResourceManager.GetString("MsgImportOfFailed", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''Wyszukuje zlokalizowany ciąg podobny do ciągu Invalid data. Could not find headers!.
        '''</summary>
        Friend Shared ReadOnly Property MsgInvalidDataCouldNotFindHeaders() As String
            Get
                Return ResourceManager.GetString("MsgInvalidDataCouldNotFindHeaders", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''Wyszukuje zlokalizowany ciąg podobny do ciągu &apos;{0}&apos; line {1} caused an exception:.
        '''</summary>
        Friend Shared ReadOnly Property MsgLineCausedException() As String
            Get
                Return ResourceManager.GetString("MsgLineCausedException", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''Wyszukuje zlokalizowany ciąg podobny do ciągu Login &apos;{0}&apos; is already assigned to another user!.
        '''</summary>
        Friend Shared ReadOnly Property MsgLoginIsAlreadyAssignedToAnotherUser() As String
            Get
                Return ResourceManager.GetString("MsgLoginIsAlreadyAssignedToAnotherUser", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''Wyszukuje zlokalizowany ciąg podobny do ciągu MRP Controller &apos;{0}&apos; is already assigned to another user!.
        '''</summary>
        Friend Shared ReadOnly Property MsgMRPControllerIsAlreadyAssignedToAnotherUser() As String
            Get
                Return ResourceManager.GetString("MsgMRPControllerIsAlreadyAssignedToAnotherUser", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''Wyszukuje zlokalizowany ciąg podobny do ciągu Number of connections increased: {0}..
        '''</summary>
        Friend Shared ReadOnly Property MsgNumberOfConnectionsIncreased() As String
            Get
                Return ResourceManager.GetString("MsgNumberOfConnectionsIncreased", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''Wyszukuje zlokalizowany ciąg podobny do ciągu Out of memeory! Splitting transaction of {0} SQL statements into two parts..
        '''</summary>
        Friend Shared ReadOnly Property MsgOutOfMemorySplittingTransactionOfSQLStatementsInto2Parts() As String
            Get
                Return ResourceManager.GetString("MsgOutOfMemorySplittingTransactionOfSQLStatementsInto2Parts", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''Wyszukuje zlokalizowany ciąg podobny do ciągu Partner &apos;{0}&apos; is already assigned to another user!.
        '''</summary>
        Friend Shared ReadOnly Property MsgPartnerIsAlreadyAssignedToAnotherUser() As String
            Get
                Return ResourceManager.GetString("MsgPartnerIsAlreadyAssignedToAnotherUser", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''Wyszukuje zlokalizowany ciąg podobny do ciągu Please click &apos;...&apos; to show selection form..
        '''</summary>
        Friend Shared ReadOnly Property MsgPleaseClick2ShowSelectionForm() As String
            Get
                Return ResourceManager.GetString("MsgPleaseClick2ShowSelectionForm", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''Wyszukuje zlokalizowany ciąg podobny do ciągu Please enter e-mail!.
        '''</summary>
        Friend Shared ReadOnly Property MsgPleaseEnterEMail() As String
            Get
                Return ResourceManager.GetString("MsgPleaseEnterEMail", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''Wyszukuje zlokalizowany ciąg podobny do ciągu Please enter a login!.
        '''</summary>
        Friend Shared ReadOnly Property MsgPleaseEnterLogin() As String
            Get
                Return ResourceManager.GetString("MsgPleaseEnterLogin", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''Wyszukuje zlokalizowany ciąg podobny do ciągu Please enter an MRP controller!.
        '''</summary>
        Friend Shared ReadOnly Property MsgPleaseEnterMRPController() As String
            Get
                Return ResourceManager.GetString("MsgPleaseEnterMRPController", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''Wyszukuje zlokalizowany ciąg podobny do ciągu Please enter a phone number!.
        '''</summary>
        Friend Shared ReadOnly Property MsgPleaseEnterPhoneNumber() As String
            Get
                Return ResourceManager.GetString("MsgPleaseEnterPhoneNumber", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''Wyszukuje zlokalizowany ciąg podobny do ciągu Please enter wire type name..
        '''</summary>
        Friend Shared ReadOnly Property MsgPleaseEnterWireTypeName() As String
            Get
                Return ResourceManager.GetString("MsgPleaseEnterWireTypeName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''Wyszukuje zlokalizowany ciąg podobny do ciągu Please read a project first!.
        '''</summary>
        Friend Shared ReadOnly Property MsgPleaseReadProjectFirst() As String
            Get
                Return ResourceManager.GetString("MsgPleaseReadProjectFirst", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''Wyszukuje zlokalizowany ciąg podobny do ciągu Please select a partner!.
        '''</summary>
        Friend Shared ReadOnly Property MsgPleaseSelectPartner() As String
            Get
                Return ResourceManager.GetString("MsgPleaseSelectPartner", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''Wyszukuje zlokalizowany ciąg podobny do ciągu Please select product..
        '''</summary>
        Friend Shared ReadOnly Property MsgPleaseSelectProduct() As String
            Get
                Return ResourceManager.GetString("MsgPleaseSelectProduct", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''Wyszukuje zlokalizowany ciąg podobny do ciągu Please select a user group!.
        '''</summary>
        Friend Shared ReadOnly Property MsgPleaseSelectUserGroup() As String
            Get
                Return ResourceManager.GetString("MsgPleaseSelectUserGroup", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''Wyszukuje zlokalizowany ciąg podobny do ciągu Please select a user type!.
        '''</summary>
        Friend Shared ReadOnly Property MsgPleaseSelectUserType() As String
            Get
                Return ResourceManager.GetString("MsgPleaseSelectUserType", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''Wyszukuje zlokalizowany ciąg podobny do ciągu Please select wire color..
        '''</summary>
        Friend Shared ReadOnly Property MsgPleaseSelectWireColor() As String
            Get
                Return ResourceManager.GetString("MsgPleaseSelectWireColor", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''Wyszukuje zlokalizowany ciąg podobny do ciągu Please select wire cross section..
        '''</summary>
        Friend Shared ReadOnly Property MsgPleaseSelectWireCrossSection() As String
            Get
                Return ResourceManager.GetString("MsgPleaseSelectWireCrossSection", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''Wyszukuje zlokalizowany ciąg podobny do ciągu Please wait some seconds/minutes to repeat the execution..
        '''</summary>
        Friend Shared ReadOnly Property MsgPleaseWaitSomeSecondsMinutesToRepeatExecution() As String
            Get
                Return ResourceManager.GetString("MsgPleaseWaitSomeSecondsMinutesToRepeatExecution", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''Wyszukuje zlokalizowany ciąg podobny do ciągu The project already exists in the database. Do you want to overwrite?.
        '''</summary>
        Friend Shared ReadOnly Property MsgProjectAlreadyExistsInDatabaseDoYouWantToOverwrite() As String
            Get
                Return ResourceManager.GetString("MsgProjectAlreadyExistsInDatabaseDoYouWantToOverwrite", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''Wyszukuje zlokalizowany ciąg podobny do ciągu Provided material is not related!.
        '''</summary>
        Friend Shared ReadOnly Property MsgProvidedMaterialIsNotRelated() As String
            Get
                Return ResourceManager.GetString("MsgProvidedMaterialIsNotRelated", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''Wyszukuje zlokalizowany ciąg podobny do ciągu PurchaseOrder with ID = {0} not found!.
        '''</summary>
        Friend Shared ReadOnly Property MsgPurchaseOrderWithIDNotFound() As String
            Get
                Return ResourceManager.GetString("MsgPurchaseOrderWithIDNotFound", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''Wyszukuje zlokalizowany ciąg podobny do ciągu The (re-)connecting to the database failed..
        '''</summary>
        Friend Shared ReadOnly Property MsgReconnectingToDatabaseFailed() As String
            Get
                Return ResourceManager.GetString("MsgReconnectingToDatabaseFailed", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''Wyszukuje zlokalizowany ciąg podobny do ciągu Selected employee already exists..
        '''</summary>
        Friend Shared ReadOnly Property MsgSelectedEmployeeAlreadyExists() As String
            Get
                Return ResourceManager.GetString("MsgSelectedEmployeeAlreadyExists", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''Wyszukuje zlokalizowany ciąg podobny do ciągu Selected employee doesn&apos;t have a GID..
        '''</summary>
        Friend Shared ReadOnly Property MsgSelectedEmployeeDoesntHaveGID() As String
            Get
                Return ResourceManager.GetString("MsgSelectedEmployeeDoesntHaveGID", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''Wyszukuje zlokalizowany ciąg podobny do ciągu The selected material is already related with another group of materials!.
        '''</summary>
        Friend Shared ReadOnly Property MsgSelectedMaterialIsAlreadyRelatedWithAnotherGroupOfMaterials() As String
            Get
                Return ResourceManager.GetString("MsgSelectedMaterialIsAlreadyRelatedWithAnotherGroupOfMaterials", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''Wyszukuje zlokalizowany ciąg podobny do ciągu The selected material is currently viewed in the Cockpit Item!.
        '''</summary>
        Friend Shared ReadOnly Property MsgSelectedMaterialIsCurrentlyViewedInCockpitItem() As String
            Get
                Return ResourceManager.GetString("MsgSelectedMaterialIsCurrentlyViewedInCockpitItem", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''Wyszukuje zlokalizowany ciąg podobny do ciągu Selected partner cannot be deleted because is still assigned to a user!.
        '''</summary>
        Friend Shared ReadOnly Property MsgSelectedPartnerCannotBeDeletedBecauseIsStillAssigned2User() As String
            Get
                Return ResourceManager.GetString("MsgSelectedPartnerCannotBeDeletedBecauseIsStillAssigned2User", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''Wyszukuje zlokalizowany ciąg podobny do ciągu The specified wire already exists..
        '''</summary>
        Friend Shared ReadOnly Property MsgSpecifiedWireAlreadyExists() As String
            Get
                Return ResourceManager.GetString("MsgSpecifiedWireAlreadyExists", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''Wyszukuje zlokalizowany ciąg podobny do ciągu Synchronization complete..
        '''</summary>
        Friend Shared ReadOnly Property MsgSynchronizationComplete() As String
            Get
                Return ResourceManager.GetString("MsgSynchronizationComplete", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''Wyszukuje zlokalizowany ciąg podobny do ciągu Unknown data type: &apos;{0}&apos;..
        '''</summary>
        Friend Shared ReadOnly Property MsgUnknownDataType() As String
            Get
                Return ResourceManager.GetString("MsgUnknownDataType", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''Wyszukuje zlokalizowany ciąg podobny do ciągu User has some Favorites folders and cannot be deleted!.
        '''</summary>
        Friend Shared ReadOnly Property MsgUserHasSomeFavoritesFoldersAndCannotBeDeleted() As String
            Get
                Return ResourceManager.GetString("MsgUserHasSomeFavoritesFoldersAndCannotBeDeleted", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''Wyszukuje zlokalizowany ciąg podobny do ciągu User &apos;{0}&apos; is inactive!.
        '''</summary>
        Friend Shared ReadOnly Property MsgUserIsInactive() As String
            Get
                Return ResourceManager.GetString("MsgUserIsInactive", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''Wyszukuje zlokalizowany ciąg podobny do ciągu User login &apos;{0}&apos; could not be found!.
        '''</summary>
        Friend Shared ReadOnly Property MsgUserLoginCouldNotBeFound() As String
            Get
                Return ResourceManager.GetString("MsgUserLoginCouldNotBeFound", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''Wyszukuje zlokalizowany ciąg podobny do ciągu User with no. {0} could not be found!.
        '''</summary>
        Friend Shared ReadOnly Property MsgUserWithNoCouldNotBeFound() As String
            Get
                Return ResourceManager.GetString("MsgUserWithNoCouldNotBeFound", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''Wyszukuje zlokalizowany ciąg podobny do ciągu Arrival in Wuxi.
        '''</summary>
        Friend Shared ReadOnly Property TextArrivalInWuxi() As String
            Get
                Return ResourceManager.GetString("TextArrivalInWuxi", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''Wyszukuje zlokalizowany ciąg podobny do ciągu Choose Partner.
        '''</summary>
        Friend Shared ReadOnly Property TextChoosePartner() As String
            Get
                Return ResourceManager.GetString("TextChoosePartner", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''Wyszukuje zlokalizowany ciąg podobny do ciągu Column {0} has unrecognizable data: &apos;{1}&apos;.
        '''</summary>
        Friend Shared ReadOnly Property TextColumnHasUnrecognizableData() As String
            Get
                Return ResourceManager.GetString("TextColumnHasUnrecognizableData", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''Wyszukuje zlokalizowany ciąg podobny do ciągu Column {0} is out of range, cannot assign to header..
        '''</summary>
        Friend Shared ReadOnly Property TextColumnIsOutOfRangeCannotAssignToHeader() As String
            Get
                Return ResourceManager.GetString("TextColumnIsOutOfRangeCannotAssignToHeader", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''Wyszukuje zlokalizowany ciąg podobny do ciągu Common User.
        '''</summary>
        Friend Shared ReadOnly Property TextCommonUser() As String
            Get
                Return ResourceManager.GetString("TextCommonUser", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''Wyszukuje zlokalizowany ciąg podobny do ciągu Connection String: {0}.
        '''</summary>
        Friend Shared ReadOnly Property TextConnectionString() As String
            Get
                Return ResourceManager.GetString("TextConnectionString", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''Wyszukuje zlokalizowany ciąg podobny do ciągu Could not find file: &apos;{0}&apos;.
        '''</summary>
        Friend Shared ReadOnly Property TextCouldNotFindFile() As String
            Get
                Return ResourceManager.GetString("TextCouldNotFindFile", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''Wyszukuje zlokalizowany ciąg podobny do ciągu Date/Time: {0}.
        '''</summary>
        Friend Shared ReadOnly Property TextDateTime_() As String
            Get
                Return ResourceManager.GetString("TextDateTime_", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''Wyszukuje zlokalizowany ciąg podobny do ciągu Empty material no..
        '''</summary>
        Friend Shared ReadOnly Property TextEmptyMaterialNo() As String
            Get
                Return ResourceManager.GetString("TextEmptyMaterialNo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''Wyszukuje zlokalizowany ciąg podobny do ciągu Empty PONo or POItem..
        '''</summary>
        Friend Shared ReadOnly Property TextEmptyPONoOrPOItem() As String
            Get
                Return ResourceManager.GetString("TextEmptyPONoOrPOItem", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''Wyszukuje zlokalizowany ciąg podobny do ciągu Empty supplier no..
        '''</summary>
        Friend Shared ReadOnly Property TextEmptySupplierNo() As String
            Get
                Return ResourceManager.GetString("TextEmptySupplierNo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''Wyszukuje zlokalizowany ciąg podobny do ciągu ErrLog_{0}.txt.
        '''</summary>
        Friend Shared ReadOnly Property TextErrLog_Txt() As String
            Get
                Return ResourceManager.GetString("TextErrLog_Txt", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''Wyszukuje zlokalizowany ciąg podobny do ciągu Error No. {0}: {1}.
        '''</summary>
        Friend Shared ReadOnly Property TextErrorNoText() As String
            Get
                Return ResourceManager.GetString("TextErrorNoText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''Wyszukuje zlokalizowany ciąg podobny do ciągu Found and removed duplicate info set records: ({0}).
        '''</summary>
        Friend Shared ReadOnly Property TextFoundAndRemovedDuplicateInfoSetRecords() As String
            Get
                Return ResourceManager.GetString("TextFoundAndRemovedDuplicateInfoSetRecords", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''Wyszukuje zlokalizowany ciąg podobny do ciągu Found and removed duplicate material numbers: .
        '''</summary>
        Friend Shared ReadOnly Property TextFoundAndRemovedDuplicateMaterialNumbers() As String
            Get
                Return ResourceManager.GetString("TextFoundAndRemovedDuplicateMaterialNumbers", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''Wyszukuje zlokalizowany ciąg podobny do ciągu Found and removed duplicate PO Confirmations: ({0}).
        '''</summary>
        Friend Shared ReadOnly Property TextFoundAndRemovedDuplicatePOConfirmations() As String
            Get
                Return ResourceManager.GetString("TextFoundAndRemovedDuplicatePOConfirmations", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''Wyszukuje zlokalizowany ciąg podobny do ciągu Found and removed duplicate supplier numbers: .
        '''</summary>
        Friend Shared ReadOnly Property TextFoundAndRemovedDuplicateSupplierNumbers() As String
            Get
                Return ResourceManager.GetString("TextFoundAndRemovedDuplicateSupplierNumbers", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''Wyszukuje zlokalizowany ciąg podobny do ciągu Found and removed entries with duplicate material numbers:.
        '''</summary>
        Friend Shared ReadOnly Property TextFoundAndRemovedEntriesWithDuplicateMaterialNumbers() As String
            Get
                Return ResourceManager.GetString("TextFoundAndRemovedEntriesWithDuplicateMaterialNumbers", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''Wyszukuje zlokalizowany ciąg podobny do ciągu Import in progress....
        '''</summary>
        Friend Shared ReadOnly Property TextImportInProgress() As String
            Get
                Return ResourceManager.GetString("TextImportInProgress", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''Wyszukuje zlokalizowany ciąg podobny do ciągu Import SAP data.
        '''</summary>
        Friend Shared ReadOnly Property TextImportSAPData() As String
            Get
                Return ResourceManager.GetString("TextImportSAPData", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''Wyszukuje zlokalizowany ciąg podobny do ciągu Invalid end date: &apos;{0}&apos;.
        '''</summary>
        Friend Shared ReadOnly Property TextInvalidEndDate() As String
            Get
                Return ResourceManager.GetString("TextInvalidEndDate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''Wyszukuje zlokalizowany ciąg podobny do ciągu Invalid Info rec. no. or to few columns to get required data..
        '''</summary>
        Friend Shared ReadOnly Property TextInvalidInfoRecNoOrToFewColumnsToGetRequiredData() As String
            Get
                Return ResourceManager.GetString("TextInvalidInfoRecNoOrToFewColumnsToGetRequiredData", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''Wyszukuje zlokalizowany ciąg podobny do ciągu Invalid start date: &apos;{0}&apos;.
        '''</summary>
        Friend Shared ReadOnly Property TextInvalidStartDate() As String
            Get
                Return ResourceManager.GetString("TextInvalidStartDate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''Wyszukuje zlokalizowany ciąg podobny do ciągu Lead time.
        '''</summary>
        Friend Shared ReadOnly Property TextLeadTime() As String
            Get
                Return ResourceManager.GetString("TextLeadTime", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''Wyszukuje zlokalizowany ciąg podobny do ciągu Loading MLFB map.
        '''</summary>
        Friend Shared ReadOnly Property TextLoadingMLFBMap() As String
            Get
                Return ResourceManager.GetString("TextLoadingMLFBMap", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''Wyszukuje zlokalizowany ciąg podobny do ciągu Manage Partners.
        '''</summary>
        Friend Shared ReadOnly Property TextManagePartners() As String
            Get
                Return ResourceManager.GetString("TextManagePartners", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''Wyszukuje zlokalizowany ciąg podobny do ciągu Mapping data from &apos;{0}&apos; to SQL records.
        '''</summary>
        Friend Shared ReadOnly Property TextMappingDataFromToSQLRecords() As String
            Get
                Return ResourceManager.GetString("TextMappingDataFromToSQLRecords", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''Wyszukuje zlokalizowany ciąg podobny do ciągu Mapping data to SQL records.
        '''</summary>
        Friend Shared ReadOnly Property TextMappingDataToSQLRecords() As String
            Get
                Return ResourceManager.GetString("TextMappingDataToSQLRecords", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''Wyszukuje zlokalizowany ciąg podobny do ciągu Next import in {0}.
        '''</summary>
        Friend Shared ReadOnly Property TextNextImportIn_() As String
            Get
                Return ResourceManager.GetString("TextNextImportIn_", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''Wyszukuje zlokalizowany ciąg podobny do ciągu only valid info sets.
        '''</summary>
        Friend Shared ReadOnly Property TextOnlyValidInfoSets() As String
            Get
                Return ResourceManager.GetString("TextOnlyValidInfoSets", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''Wyszukuje zlokalizowany ciąg podobny do ciągu only valid info sets with open POs.
        '''</summary>
        Friend Shared ReadOnly Property TextOnlyValidInfoSetsWithOpenPOs() As String
            Get
                Return ResourceManager.GetString("TextOnlyValidInfoSetsWithOpenPOs", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''Wyszukuje zlokalizowany ciąg podobny do ciągu Parsing: &apos;{0}&apos;..
        '''</summary>
        Friend Shared ReadOnly Property TextParsing() As String
            Get
                Return ResourceManager.GetString("TextParsing", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''Wyszukuje zlokalizowany ciąg podobny do ciągu Partner - Edit.
        '''</summary>
        Friend Shared ReadOnly Property TextPartnerEdit() As String
            Get
                Return ResourceManager.GetString("TextPartnerEdit", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''Wyszukuje zlokalizowany ciąg podobny do ciągu Partner - New.
        '''</summary>
        Friend Shared ReadOnly Property TextPartnerNew() As String
            Get
                Return ResourceManager.GetString("TextPartnerNew", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''Wyszukuje zlokalizowany ciąg podobny do ciągu Partner - View.
        '''</summary>
        Friend Shared ReadOnly Property TextPartnerView() As String
            Get
                Return ResourceManager.GetString("TextPartnerView", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''Wyszukuje zlokalizowany ciąg podobny do ciągu Reading data from: &apos;{0}&apos;..
        '''</summary>
        Friend Shared ReadOnly Property TextReadingDataFrom() As String
            Get
                Return ResourceManager.GetString("TextReadingDataFrom", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''Wyszukuje zlokalizowany ciąg podobny do ciągu Reading data ({0} lines).
        '''</summary>
        Friend Shared ReadOnly Property TextReadingDataLines() As String
            Get
                Return ResourceManager.GetString("TextReadingDataLines", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''Wyszukuje zlokalizowany ciąg podobny do ciągu SAPImport_{0}.txt.
        '''</summary>
        Friend Shared ReadOnly Property TextSAPImport_Txt() As String
            Get
                Return ResourceManager.GetString("TextSAPImport_Txt", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''Wyszukuje zlokalizowany ciąg podobny do ciągu Size: {0}B | {1}KB | {2}MB.
        '''</summary>
        Friend Shared ReadOnly Property TextSizeBKBMB() As String
            Get
                Return ResourceManager.GetString("TextSizeBKBMB", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''Wyszukuje zlokalizowany ciąg podobny do ciągu Skipping column from line {0}. Cause: .
        '''</summary>
        Friend Shared ReadOnly Property TextSkippingColumnFromLineCause() As String
            Get
                Return ResourceManager.GetString("TextSkippingColumnFromLineCause", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''Wyszukuje zlokalizowany ciąg podobny do ciągu Skipping line {0}. Cause: .
        '''</summary>
        Friend Shared ReadOnly Property TextSkippingLineCause() As String
            Get
                Return ResourceManager.GetString("TextSkippingLineCause", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''Wyszukuje zlokalizowany ciąg podobny do ciągu Supervisor.
        '''</summary>
        Friend Shared ReadOnly Property TextSupervisor() As String
            Get
                Return ResourceManager.GetString("TextSupervisor", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''Wyszukuje zlokalizowany ciąg podobny do ciągu To few columns to get required data..
        '''</summary>
        Friend Shared ReadOnly Property TextToFewColumnsToGetRequiredData() As String
            Get
                Return ResourceManager.GetString("TextToFewColumnsToGetRequiredData", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''Wyszukuje zlokalizowany ciąg podobny do ciągu Unknown PaymentTerm: &apos;{0}&apos;.
        '''</summary>
        Friend Shared ReadOnly Property TextUnknownPaymentTerm() As String
            Get
                Return ResourceManager.GetString("TextUnknownPaymentTerm", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''Wyszukuje zlokalizowany ciąg podobny do ciągu User - Edit.
        '''</summary>
        Friend Shared ReadOnly Property TextUserEdit() As String
            Get
                Return ResourceManager.GetString("TextUserEdit", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''Wyszukuje zlokalizowany ciąg podobny do ciągu User - New.
        '''</summary>
        Friend Shared ReadOnly Property TextUserNew() As String
            Get
                Return ResourceManager.GetString("TextUserNew", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''Wyszukuje zlokalizowany ciąg podobny do ciągu User - View.
        '''</summary>
        Friend Shared ReadOnly Property TextUserView() As String
            Get
                Return ResourceManager.GetString("TextUserView", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
